### ISSUE TITLE
The possibility of quoted coordinate values should be considered

### ISSUE THREAD

**Issue by markstos** [Turfjs/turf-point#6] opened 2015-10-05 18:08 UTC
Currently if quoted coordinate values are passed in, a "garbage-in, garbage-out" situation occurs: A result is produced that also quotes the coordinate values. This is not valid GeoJSON, which specifies that coordinate values must be _numbers_, while quoting the values  makes them _strings_.

There a a couple reasonable resolutions:
1. **Reject quoted values** The code is already strict that the value of `coordinates` must be an array, and the length is also checked. One more check could be made to check that the coordinate values are numbers. 
2.  **cast coordinate values with `Number()`**  This allows accepted quoted values. Bad values can detected by checking if the result is `NaN`, and throwing an error in that case.

This case should also be considered along with the handling of quoted coordinate values in `turf-midpoint`. See the related pull request there:
- [Support quoted coordinate values in turf-midpoint.](https://github.com/Turfjs/turf-midpoint/pull/3)

**Comment by markstos** [comment] 2015-10-06 14:43
After sleeping on it, I think the better approach is to validate that the input are numbers and throw an exception if the input are not numbers. 

Providing a String type when the Number type is expected indicates a possible bug in the calling code, and it's better to notify the developer about the issue through an exception then to allow a potential "Garbage-In / Garbage Out" state of translating a string to a number. The documentation could be updated to note that if you want to provide the input as strings, you can easily explicitly do the conversion yourself:

``` javascript
var pt1 = turf.point([Number("a"), Number("b")]);
```

If you agree, I could put together a pull request if you'd like.

**Comment by morganherlocker** [comment] 2015-10-06 14:58
In my opinion, this should be the user's responsibility to test. The documentation is very clear about the required types, and strings as coordinates do not make sense as inputs. Adding checks in turf-point will cause performance regressions all over the place, since it is used in hot loops of many algorithms. While turf-point may only have 2 numbers to check each time, the other feature types could have thousands of types to check with each call. 

This question comes up from time to time, and I always suggest the following, which seems to solve the problem for every user so far:
1. Read the [GeoJSON spec](http://geojson.org/geojson-spec.html); this is required reading for Turf, since it is the central data structure of the library.
2. Read the documentation of the module you are using.
3. Make sure your data is actually what you think it is using a tool like geojson.io
4. Write tests and validate unknown input values at runtime

For someone following these 4 pieces of advice, I just do not foresee this being a problem for anyone.

**Comment by markstos** [comment] 2015-10-06 15:07
Thanks for the response. I appreciate the concern of not adding anything extra to a function used in a hot loop.

**Comment by morganherlocker** [comment] 2015-10-06 15:11
Closing this, but thanks for the suggestion @markstos.

**Closed as completed by morganherlocker** 2015-10-06 15:11 UTC

**Comment by markstos** [comment] 2015-10-06 15:23
Although, from checking this benchmark, it looks like `typeof` checks can run at a speed of something like 90 million times per second: https://jsperf.com/check-js-type

Based on that, it would appear that adding the extra checks for robustness would only a few milliseconds to run time even when there  are  ~1 million `turf.point` operations. 

Another option is to provide a separate `validatePoint()` method, which developers can optionally call if they are willing to take spend a few millionths of a second extra to check the input before passing it to  `turf.point`. Developers are dealing with known-to-be-pre-validated data can skip the extra check.
